author: Eric Jorgenson
color: '#DD4124'
cover: https://covers.openlibrary.org/b/id/10449931-M.jpg
status: reading
rating: 5
tags: [finance, life-advice]
title: The Almanack of Naval Ravikant
totalChapters: 10
