author: Benjamin Graham
color: '#55B4B0'
cover: https://covers.openlibrary.org/b/id/36434-M.jpg
status: reading
rating: 5
tags: [finance, investment]
title: The Intelligent Investor
totalChapters: 20
