author: Mr. Parag Parikh
color: '#6B5B95'
cover: https://covers.openlibrary.org/b/id/11107314-M.jpg
status: reading
rating: 5
tags: [finance, investment]
title: Value Investing and Behavioral Finance
totalChapters: 10
